language: ruby
cache:
  - bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'o
install: bundle install
after_success:
  - coveralls
