language: ruby
cache:
  - bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - sudo apt-get update -qq
  - sudo apt-get install -y alsa-utils pulseaudio
  - sudo modprobe snd-dummy
  - 'echo ''pcm.pulse { type pulse }'' > ~/.asoundrc'
  - 'echo ''ctl.pulse { type pulse }'' > ~/.asoundrc'
  - 'echo ''pcm.!defautl { type pulse }'' > ~/.asoundrc'
  - 'echo ''ctl.!default { type pulse }'' > ~/.asoundrc'
  - pactl list
install: bundle install
after_success:
  - coveralls
