language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.1.4
  - ruby-head
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - apt-get update -qq
  - apt-get install -y alsamixer alsa-utils pulseaudio
install: bundle install
after_success:
  - coveralls
