language: ruby
cache:
  - apt
  - bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - sudo amixer -h | head -n 1
  - sudo apt-get update -qq
  - sudo apt-get install -y alsa-utils pulseaudio
install: bundle install
after_success:
  - coveralls
