language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.1.4
  - ruby-head
before_script:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - sudo apt-get update -q
  - sudo apt-get install -y alsa-utils alsamixer pulseaudio
install: bundle install