---
light:
  - "brightness = `cat /sys/class/backlight/intel_backlight/brightness`.to_i"
  - "exit if @backlight == 'nil' && brightness == 0"
players:
  - "%w(xbmc kodi vlc).each do |player|"
  - "exit if `ps -el | grep '#{player}' | wc -l`.to_i > 0"
  - "end"
