---
light:
  - "brightness = `cat /sys/class/backlight/intel_backlight/brightness`.to_i"
  - "exit if @backlight == 'nil' && brightness == 0"
flash:
  - "displays = `xvinfo`.scan(/screen\\s#(\\d+)/i).flatten"
  - "displays.each do |display|"
  - "  display = display.eql?('0') ? '' : '.' + display"
  - "  active = `DISPLAY=:0#{display} xprop -root '_NET_ACTIVE_WINDOW'`.scan(/\\w+/).last"
  - "  unless `xprop -id '#{active}' | grep '_NET_WM_STATE_FULLSCREEN'`.empty?"
  - "    wm_class = `xprop -id '#{active}' | grep 'WM_CLASS(STRING)'`"
  - "    ['unknown', 'plugin-containe', 'exe'].each do |name|"
  - "      exit if wm_class.scan(name).last == name"
  - "    end"
  - "    wm_name = `xprop -id '#{active}' | grep '_NET_WM_NAME(UTF8_STRING)'`"
  - "    exit unless wm_name.scan(/YouTube/i).empty?"
  - "  end"
  - "end"
skype:
  - "exit unless `pactl list sink-inputs | grep 'phone'`.empty?"
players:
  - "%w(xbmc kodi vlc popcorntime).each do |player|"
  - "  exit if `ps -el | grep '#{player}' | wc -l`.to_i > 0"
  - "end"
